Завдання 1.
27. Створіть одновимірний масив (вектор) зі значеннями 2
𝑛 для кожного натурального
числа n, починаючи з 0, та виведіть його значення.

In [2]:
import numpy as np

# Визначаємо розмір масиву
size = 10

# Створюємо масив зі значеннями 2^n
powers_of_two = [2 ** n for n in range(size)]

# Виводимо значення масиву на екран
print("Масив значень 2^n:")
for value in powers_of_two:
    print(value)

Масив значень 2^n:
1
2
4
8
16
32
64
128
256
512



Завдання 2.
27. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями простих чисел.

In [3]:
import numpy as np

# Функція для перевірки, чи є число простим
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i == 0:
            return False
    return True

# Генеруємо список простих чисел
def generate_primes(count):
    primes = []
    num = 2
    while len(primes) < count:
        if is_prime(num):
            primes.append(num)
        num += 1
    return primes

# Визначаємо розмір матриці
rows, cols = 3, 3

# Генеруємо 9 простих чисел
prime_numbers = generate_primes(rows * cols)

# Створюємо матрицю 3x3 і заповнюємо її простими числами
matrix = np.array(prime_numbers).reshape(rows, cols)

# Виводимо матрицю на екран
print("Матриця 3x3, заповнена простими числами:")
print(matrix)


Матриця 3x3, заповнена простими числами:
[[ 2  3  5]
 [ 7 11 13]
 [17 19 23]]


Завдання 3.
27. Створіть масив розміром 5x5, заповніть його випадковими цілими числами від -50 до 50.

In [4]:
import numpy as np

# Визначаємо розмір масиву
rows, cols = 5, 5

# Створюємо масив 5x5 і заповнюємо його випадковими числами від -50 до 50
matrix = np.random.randint(-50, 51, size=(rows, cols))

# Виводимо масив на екран
print("Масив 5x5, заповнений випадковими числами від -50 до 50:")
print(matrix)


Масив 5x5, заповнений випадковими числами від -50 до 50:
[[ 32   1 -46   2  45]
 [ 41 -31  24  34   8]
 [-33  -7 -45 -42 -20]
 [-18  37  29 -13  31]
 [-18  22  -2  47 -38]]


Завдання 4.
27. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в  діапазоні від -1.3 до 1.3 та виведіть його значення.

In [5]:
import numpy as np

# Визначаємо розмір масиву
rows, cols = 3, 3

# Створюємо масив 3x3 і заповнюємо його випадковими дійсними числами від -1.3 до 1.3
matrix = np.random.uniform(-1.3, 1.3, size=(rows, cols))

# Виводимо масив на екран
print("Масив 3x3, заповнений випадковими дійсними числами від -1.3 до 1.3:")
print(matrix)


Масив 3x3, заповнений випадковими дійсними числами від -1.3 до 1.3:
[[-0.97987257 -1.00852969 -0.85534209]
 [ 0.96361606 -0.56855776  0.1673624 ]
 [ 0.41699828 -1.08599189  0.46384948]]


Завдання 5.
27. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими
числами в діапазоні від 10 до 15 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [6]:
import numpy as np

# Визначаємо розмір масивів
size = 7

# Створюємо два масиви та заповнюємо їх випадковими цілими числами від 10 до 15
array1 = np.random.randint(10, 16, size)
array2 = np.random.randint(10, 16, size)

# Виконуємо поелементні операції додавання, віднімання та множення
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виводимо результати на екран
print("Перший масив:")
print(array1)

print("\nДругий масив:")
print(array2)

print("\nРезультат додавання:")
print(addition)

print("\nРезультат віднімання:")
print(subtraction)

print("\nРезультат множення:")
print(multiplication)


Перший масив:
[11 11 11 14 14 13 13]

Другий масив:
[13 13 13 10 11 14 11]

Результат додавання:
[24 24 24 24 25 27 24]

Результат віднімання:
[-2 -2 -2  4  3 -1  2]

Результат множення:
[143 143 143 140 154 182 143]


Завдання 6.
27. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та
знайдіть їх добуток.

In [7]:
import numpy as np

# Визначаємо розмір матриць
rows, cols = 4, 4

# Створюємо дві матриці 4x4 та заповнюємо їх випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(rows, cols))
matrix2 = np.random.randint(1, 11, size=(rows, cols))

# Обчислюємо добуток двох матриць
product_matrix = np.dot(matrix1, matrix2)

# Виводимо матриці та їхній добуток на екран
print("Перша матриця:")
print(matrix1)

print("\nДруга матриця:")
print(matrix2)

print("\nДобуток матриць:")
print(product_matrix)


Перша матриця:
[[ 4  1  1  4]
 [ 8  2  1  2]
 [ 5  7  4  4]
 [10  5  5 10]]

Друга матриця:
[[ 3  8  5  1]
 [10  8  1  2]
 [ 4  3  8  8]
 [ 9  5  9  6]]

Добуток матриць:
[[ 62  63  65  38]
 [ 66  93  68  32]
 [137 128 100  75]
 [190 185 185 120]]


Завдання 7.
27. Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 7 та перемножте їх між собою.

In [8]:
import numpy as np

# Визначаємо розміри матриць
rows1, cols1 = 2, 3
rows2, cols2 = 3, 2

# Створюємо матриці з випадковими цілими числами від 1 до 7
matrix1 = np.random.randint(1, 8, size=(rows1, cols1))
matrix2 = np.random.randint(1, 8, size=(rows2, cols2))

# Обчислюємо добуток матриць
product_matrix = np.dot(matrix1, matrix2)

# Виводимо матриці та їхній добуток на екран
print("Перша матриця (2x3):")
print(matrix1)

print("\nДруга матриця (3x2):")
print(matrix2)

print("\nДобуток матриць (2x2):")
print(product_matrix)


Перша матриця (2x3):
[[3 2 2]
 [4 1 6]]

Друга матриця (3x2):
[[3 5]
 [3 2]
 [3 6]]

Добуток матриць (2x2):
[[21 31]
 [33 58]]


Завдання 8.
27. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 8 та знайдіть її обернену матрицю.

In [9]:
import numpy as np

# Визначаємо розмір матриці
size = 2

# Створюємо матрицю 2x2 з випадковими цілими числами від 1 до 8
matrix = np.random.randint(1, 9, size=(size, size))

# Функція для обчислення оберненої матриці
def inverse_matrix(mat):
    try:
        inv_mat = np.linalg.inv(mat)
        return inv_mat
    except np.linalg.LinAlgError:
        return "Матриця не є оберненою (сингулярна або нестабільна)."

# Обчислюємо обернену матрицю
inverse_mat = inverse_matrix(matrix)

# Виводимо матрицю та її обернену матрицю на екран
print("Матриця 2x2:")
print(matrix)

print("\nОбернена матриця 2x2:")
print(inverse_mat)


Матриця 2x2:
[[3 5]
 [6 5]]

Обернена матриця 2x2:
[[-0.33333333  0.33333333]
 [ 0.4        -0.2       ]]


Завдання 9.
27. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в  діапазоні від 0 до 1 та транспонуйте її.

In [10]:
import numpy as np

# Визначаємо розмір матриці
rows, cols = 3, 3

# Створюємо матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(rows, cols))

# Транспонуємо матрицю
transposed_matrix = np.transpose(matrix)

# Виводимо матрицю та її транспоновану версію на екран
print("Матриця 3x3:")
print(matrix)

print("\nТранспонована матриця 3x3:")
print(transposed_matrix)


Матриця 3x3:
[[0.25234864 0.96382436 0.86398316]
 [0.33819431 0.34443512 0.83630838]
 [0.34404712 0.81300991 0.84992129]]

Транспонована матриця 3x3:
[[0.25234864 0.33819431 0.34404712]
 [0.96382436 0.34443512 0.81300991]
 [0.86398316 0.83630838 0.84992129]]


Завдання 10.
27. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.


In [11]:
import numpy as np

# Визначаємо розміри матриці та вектора
rows_matrix, cols_matrix = 3, 4
rows_vector, cols_vector = 4, 1

# Створюємо матрицю 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(rows_matrix, cols_matrix))

# Створюємо вектор 4x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(rows_vector, cols_vector))

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо матрицю, вектор та їхній добуток на екран
print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 3x4:
[[ 4  5  3  7]
 [ 4  7  3  9]
 [ 1  5 10  3]]

Вектор 4x1:
[[4]
 [4]
 [3]
 [6]]

Добуток матриці на вектор:
[[ 87]
 [107]
 [ 72]]


Завдання 11.
27. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
від 0 до 1, і знайдіть добуток матриці на вектор.


In [12]:
import numpy as np

# Визначаємо розміри матриці та вектора
rows_matrix, cols_matrix = 2, 3
rows_vector, cols_vector = 3, 1

# Створюємо матрицю 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(rows_matrix, cols_matrix))

# Створюємо вектор 3x1 з випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=(rows_vector, cols_vector))

# Обчислюємо добуток матриці на вектор
product = np.dot(matrix, vector)

# Виводимо матрицю, вектор та їхній добуток на екран
print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

print("\nДобуток матриці на вектор:")
print(product)


Матриця 2x3:
[[0.4475546  0.8538758  0.66272944]
 [0.48021142 0.28592194 0.45753233]]

Вектор 3x1:
[[0.82672386]
 [0.57581104]
 [0.85813907]]

Добуток матриці на вектор:
[[1.43038921]
 [0.95426562]]


Завдання 12.
27. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в  діапазоні від -1 до 5 та знайдіть різницю всіх елементів першої матриці.

In [13]:
import numpy as np

# Визначаємо розмір матриць
rows, cols = 3, 3

# Створюємо дві матриці 3x3 з випадковими цілими числами від -1 до 5
matrix1 = np.random.randint(-1, 6, size=(rows, cols))
matrix2 = np.random.randint(-1, 6, size=(rows, cols))

# Знаходимо різницю всіх елементів першої матриці
difference_matrix1 = np.sum(matrix1) - np.min(matrix1)

# Виводимо матриці та різницю всіх елементів першої матриці на екран
print("Перша матриця 3x3:")
print(matrix1)

print("\nДруга матриця 3x3:")
print(matrix2)

print("\nРізниця всіх елементів першої матриці:")
print(difference_matrix1)


Перша матриця 3x3:
[[ 5 -1  5]
 [ 1  4  2]
 [ 1  0  0]]

Друга матриця 3x3:
[[ 5  3  1]
 [ 1  2  0]
 [ 5  2 -1]]

Різниця всіх елементів першої матриці:
18


Завдання 13.
27. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть суму їх елементів.

In [15]:
import numpy as np

# Створення двох матриць 2x2 з випадковими дійсними числами від -1 до 1
matrix1 = np.random.uniform(-1, 1, (2, 2))
matrix2 = np.random.uniform(-1, 1, (2, 2))

# Обчислення суми елементів кожної матриці
sum_matrix1 = np.sum(matrix1)
sum_matrix2 = np.sum(matrix2)

# Виведення результатів
print("Перша матриця:\n", matrix1)
print("Сума елементів першої матриці:", sum_matrix1)

print("\nДруга матриця:\n", matrix2)
print("Сума елементів другої матриці:", sum_matrix2)
print(total_sum)


Перша матриця:
 [[ 0.28996201  0.11386531]
 [-0.38262215 -0.96692931]]
Сума елементів першої матриці: -0.9457241383132893

Друга матриця:
 [[ 0.1345773  -0.19373184]
 [-0.46082738  0.84112513]]
Сума елементів другої матриці: 0.3211432055086725
2.001307498563887


Завдання 14.
27. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -10 до 10 та знайдіть середнє значення елементів на головній діагоналі.

In [16]:
import numpy as np

# Створення матриці 3x3 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, (3, 3))

# Обчислення середнього значення елементів на головній діагоналі
diagonal_elements = np.diag(matrix)
mean_diagonal = np.mean(diagonal_elements)

# Виведення результатів
print("Матриця 3x3:\n", matrix)
print("Елементи на головній діагоналі:", diagonal_elements)
print("Середнє значення елементів на головній діагоналі:", mean_diagonal)


Матриця 3x3:
 [[ 8.53435232  7.04690975 -5.13023439]
 [-0.30082626 -6.58663106  2.17114493]
 [ 6.28880008 -9.2409484  -6.42147955]]
Елементи на головній діагоналі: [ 8.53435232 -6.58663106 -6.42147955]
Середнє значення елементів на головній діагоналі: -1.4912527663793371


Завдання 15.
27. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить найбільше за модулем
значення елементу у кожному стовпці матриці.

In [17]:
import numpy as np

# Створення матриці 4x4 з випадковими дійсними числами від -0.5 до 0.5
matrix = np.random.uniform(-0.5, 0.5, (4, 4))

# Знаходження найбільших за модулем значень у кожному стовпці
max_abs_values = np.max(np.abs(matrix), axis=0)

# Виведення результатів
print("Матриця 4x4:\n", matrix)
print("\nВектор-стовпчик з найбільшими за модулем значеннями у кожному стовпці:\n", max_abs_values)


Матриця 4x4:
 [[ 0.48731088  0.20368863  0.05498761  0.37631825]
 [ 0.27989057  0.11651896 -0.31618008  0.11467565]
 [ 0.04015127  0.42355663  0.14979118 -0.35452456]
 [-0.44083075  0.25333077  0.13800518 -0.27488679]]

Вектор-стовпчик з найбільшими за модулем значеннями у кожному стовпці:
 [0.48731088 0.42355663 0.31618008 0.37631825]


Висновок: Висновок: Засвоїли використання ColabGoogle. Ми навчилися створювати матриці різних розмірів та заповнювати їх випадковими значеннями у заданих діапазонах.Знаходження суми всіх елементів матриць. Визначення суми елементів на основній та побічній діагоналях матриці. Матричні операції: Виконання матричних операцій, таких як добуток матриці на вектор.